### ISSUE TITLE
colors module, add `fill` property to affect svg elements

### ISSUE THREAD

**Issue by noeldelgado** [basscss/addons#12]
Hi, would you consider adding the `fill` property on the colors module so we can apply those selectors on svg elements too?

A common thing, at least for me, is that I always tend to extend those class selectors, the reason for this is because I commonly use svg sprites for my icons and it is pretty easy to just add one of those classes to change its color.

This is an example of the use case I am referring to: https://jsfiddle.net/gqm2gq32/

**Comment by jxnblk** [comment]
I tend to suggest setting `fill: currentcolor` for use with svg icons. Is there any reason that wouldn't work in your case?

**Comment by noeldelgado** [comment]
OMG!, that is pretty clever actually, I am closing this and leaving this updated fiddle just for the record (https://jsfiddle.net/nLn5m5cn/).

Thank you Brent
