### ISSUE TITLE
Does basscss-forms assume .border-box?

### ISSUE THREAD

**Issue by olizilla** [basscss/addons#13]
The styles in basscss-forms seem to only play nice with margin and padding rules of the parent if each input is also given a `.border-box` class. Without it all `.input` elements are too wider for their container. `.textarea` and `.select` are also affected.

Am I missing something or should the forms module be setting `border-box` for us?

**Comment by jxnblk** [comment]
Yes, I should probably either mention that in the docs or just add `box-sizing` to the styles that depend on that.

**Comment by olizilla** [comment]
@jxnblk I'll send a PR that adds `box-sizing` to them.
