### ISSUE TITLE
Consistency: btn-outline and btn

### ISSUE THREAD

**Issue by clintonhalpin** [basscss/addons#14]
I think you'd want `.btn` and `.btn-outline` to have the same default appearance. The `btn-outline` add's border radius while the `btn` module dosen't. 

Heres what it looks like out of the box with btn 1.1.1 and btn-outline 1.1.1

![screen shot 2016-03-17 at 10 14 55 pm](https://cloud.githubusercontent.com/assets/523933/13866615/b5aa5b1a-ec8d-11e5-86c0-bf9b1174ac94.png)

**Comment by jxnblk** [comment]
Sorry, maybe it's not obvious, but the `btn` style is only meant for structural styles and intentionally doesn't include any presentational styles (e.g. border radius). For a solid button, you should use something like `btn-primary`.

**Comment by clintonhalpin** [comment]
That makes total sense! Thanks for following up
