### ISSUE TITLE
basscss-forms not accessible from npmcdn from /css directory...

### ISSUE THREAD

**Issue by michelob** [basscss/addons#17]
Hi,

The read me: https://github.com/basscss/addons/blob/master/README.md

indicates you can grab the css from npmcdn, like:

<link href="https://npmcdn.com/basscss-responsive-margin@1.1.0/css/responsive-margin.css" rel="stylesheet">

Works for:

https://npmcdn.com/basscss-colors/
https://npmcdn.com/basscss-colors@2.2.0/css/colors.css <-- exists

But doesn't work, for forms:

https://npmcdn.com/basscss-forms/
https://npmcdn.com/basscss-forms@1.0.0/css/forms.css <-- does not exist

Instead I can access here:

https://npmcdn.com/basscss-forms@1.0.0/index.css

I don't know if forms should be accessible under css, but I did get confused here.

**Comment by jxnblk** [comment]
I'm not sure what the best solution for this is, but the CSS folder in some of the modules is where the transpiled code is written and index.css represents the source. In the case of forms, that module isn't using any syntax that requires transpiling, so it only has the source.

I would like to make the links parallel but also don't want too much code duplication or unnecessary build processes slowing down installs. I'd love to hear more thoughts on the matter though.
