### ISSUE TITLE
Why is .mb2 embedded in form addon elements?

### ISSUE THREAD

**Issue by cayuu** [basscss/addons#18]
There's a `margin-bottom: 1rem` embedded in inputs, selects and textareas in the form addon.

Is this for convenience (i.e. an assumption that `.mb2` would always be used on inputs, selects and textareas anyway, so it preempts), or is there another reason (best-practice, a11y, something else)?

It doesn't seem to derive from `--space-2` either (appears hardcoded, but maybe this is just output and I'm missing the generator - can't say I looked hard).

I personally end up writing a custom override (:metal:) for this margin-bottom declaration and handling form element spacing manually. But was just curious as to its rationale.

**Comment by jxnblk** [comment]
It's meant to be a smart default that's easy to override with .mb0 or whatever you need. If this particular module isn't suiting your needs, I'd recommend forking or creating your own. I find that button and form styles are too varied from project to project to create a good one-size-fits-all solution.
