### ISSUE TITLE
border-width

### ISSUE THREAD

**Issue by dmackerman** [basscss/addons#19]
Might be worth looking into adding `border-width` customizability. 

``` css
.border-width-1
.border-width-5
```

Or maybe similar to the padding utilities.

`bw2`
`bwx1`
`bwl2 bwlr2`

Maybe too verbose.

**Comment by bhavybarca** [comment]
@dmackerman  i would like to contribute to this issue, is it still open?

**Comment by dmackerman** [comment]
Hmm, maybe? 😄 

Haven't used this library in several years.
