### ISSUE TITLE
Don't like the add on separation!

### ISSUE THREAD

**Issue by rajinder-yadav** [basscss/addons#27]
Now I am having to pull in stuff I need, and the code bloat by doing npm install for each module. I rather save space on my drive thank you very much!

It's really annoying to have to pull in all these "plug-ins", I rather have a single minified version! Ya I know about CDN, this still stinks.

Also thanks for increasing network bandwidth of having to do multiple DL, because the internet needs more noise and latency to download stuff! Having a single DL would be a lot faster than this solution IMHO! #

**Comment by rbeatty** [comment]
Have you seen [ace](https://github.com/basscss/ace)? It's the core Basscss and all optional modules - still npm but you don't have to install every module individually. Otherwise, you could always use v7 which has one minified file.

**Comment by rajinder-yadav** [comment]
Thanks @rbeatty, and apologies if I came off rude. I will take a look at ace, sounds like what I was looking for at the time.

Closing issue as resolved.
