### ISSUE TITLE
Forms in v8 - seem to not honor col-x, block vs inline

### ISSUE THREAD

**Issue by RickCogley** [basscss/addons#6]
Hi - thank you for what must have been an enormous amount of work on v8. I'm trying to upgrade. 

In the previous docs, it mentioned using col-n to specify width of form fields, but in v8, this no longer seems to work. 

```
<input type="email" name="emailAddress" class="col-4 email-octopus-email-address field rounded-left x-group-item" placeholder="Your Email Address">
```

Changing field to input works to get some formatting on the field, but, the col-4 no longer works, & the field just spreads out across the page. 

In addition, even though I am loading the v7 optional ui-groups css, the x-group-item does not seem to actually group the components. 

Is this expected? Do I need to set width simply using, say, inline styles. Also, should the x-group-item still work if I have those styles loaded, e.g: 

```
/* Basscss UI Utility Groups */

.x-group-item { margin-left: -var(--border-width) }
.x-group-item:first-of-type { margin-left: 0 }

.y-group-item { margin-top: -var(--border-width) }
.y-group-item:first-of-type { margin-top: 0 }

.x-group-item:focus,
.y-group-item:focus {
  position: relative;
  z-index: 1;
}
```

Please advise, thanks!

**Comment by RickCogley** [comment]
Another thing I noticed about forms is, the default basscss-forms in vs has them styled as block elements. If I use my v7 markup as is, with v8, it leads to: 

```
Label
[input text field]
[submit]
```

... but what I want is to have them inlined: 

```
Label [input] [submit]
```

This worked by default before, but something changed. I tried a number of things like adding the utility classes `inline`, `inline-block` and so on, on the various parts of the form and its surrounding divs, but I cannot seem to get it to stop being in block mode. Appreciate any advice here. This is where I'm working on it: 

```
<footer class="deco bold py2 m0 border-top white border-darken-4 bg-darken-4">
    <div class="flex items-baseline flex-wrap px1">
        Footer links, Social icons, Copyright etc
    </div>
    <div class="bg-darken-1">
        <div class="m1 mx-auto">
            <div class="center">

                <span class="email-octopus-success-message"></span>
                <span class="email-octopus-error-message"></span>
                <form method="post" action="https://emailoctopus.com/lists/11111111-2222-3333-4444-5555555/members/external-add" class="email-octopus-form clearfix inline-block m1">
                    <label>Get Email Updates: </label>
                    <input type="email" name="emailAddress" class="email-octopus-email-address input bg-teal bg-lighten-1 rounded-left x-group-item" placeholder="Your Email Address">
                    <button type="submit" class="btn btn-primary bg-lighten-2 rounded-right x-group-item">Subscribe</button>
                    <span class="email-octopus-form-row-honeypot">
                        <label>Protecting against bot signups - leave this field blank</label>
                        <input type="text" name="hp64dbf442-b268-11e5-b4ea-0a4287b2e8c5" autocomplete="off">
                    </span>

                </form>
            </div>
        </div>
    </div>
</footer>
```

**Comment by RickCogley** [comment]
@jxnblk you'd mentioned on my issue about the button coloring, that it could be order of import. I currently am loading the modules in this order and am wondering if that's a part of the problem. Originally I had forms with the other optional stuff, but saw that I had had it loaded before layout in v7. So I moved it there, but, it does not make a difference. 

```
/*
 * Originally Bassplate http://github.com/basscss/bassplate
 */

/* Basscss base reset "basic" new in v8 */
/*@import 'basscss-basic';*/
/*Instead use rccreset*/
@import '../reset/rccreset.css';

/* Basscss Modules (needs postcss-import to inline)*/

@import 'basscss-type-scale';
@import 'basscss-typography';

@import 'basscss-forms';

@import 'basscss-layout';
@import 'basscss-align';
@import 'basscss-margin';
@import 'basscss-padding';
@import 'basscss-grid';
@import 'basscss-flexbox';
@import 'basscss-position';
@import 'basscss-border';
@import 'basscss-hide';

/* Optional Basscss Modules (not included in Basscss by default) */
/*

/*
@import 'basscss-media-object';
@import 'basscss-input-range';
@import 'basscss-progress';
*/
@import 'basscss-all';

@import 'basscss-responsive-margin';
@import 'basscss-responsive-padding';
@import 'basscss-btn';
@import 'basscss-btn-primary';
@import 'basscss-btn-outline';
@import 'basscss-btn-sizes';
@import 'basscss-colors';
@import 'basscss-background-colors';
@import 'basscss-border-colors';
@import 'basscss-background-images';
@import 'basscss-darken';
@import 'basscss-lighten';
```

**Comment by RickCogley** [comment]
Ok, I feel really dull. I aded that col-4 back after restarting my npm start, and it works again. No idea why that would have not been taking hold, but, adding the col-4 back where it was, definitely controls the width of the input text field.

**Comment by jxnblk** [comment]
I'm guessing that might've been a source order issue. Let me know if you're still having problems.

**Comment by RickCogley** [comment]
Thanks @jxnblk. The `x-group-item` definitely does not seem to work like it used to, though. Previously it kind of neatly pulled the form elements together, but now they stay separate. I am ignoring it for now, but it would be nice if this would work.
