### ISSUE TITLE
Button color overrides do not seem to work in v8

### ISSUE THREAD

**Issue by RickCogley** [basscss/addons#7]
Hello - upgrading to v8, I'm referring to https://github.com/basscss/addons/tree/master/modules/btn-primary, and setting my class like this: 

```
<button type="submit" class="btn btn-primary bg-red rounded-right x-group-item">Subscribe</button>
```

... but the color override does not work. 

I _can_ set the default button color, using the variables: 

```
  --button-color: var(--white);
  --button-background-color: var(--teal);
```

What can I look into to see why this might not be working?

**Comment by jxnblk** [comment]
It probably has to do with source order. You might want to import btn modules before other color modules.

**Comment by RickCogley** [comment]
And boom. That was it. I slavishly copied the order in bassplate and that produced this small glitch, I think. I'll mess with it some more to see what I can see. Thanks!
