### ISSUE TITLE
colors.css dependency not defined?

### ISSUE THREAD

**Issue by oller** [basscss/addons#8]
Hi there,

I'm bumping my bassplate from v7 to v8.  I've updated package.json, removed and rebuilt `node_modules` with a new `npm i`

The error i'm getting is within the `node_modules/basscss-addons/modules/colors/index.css` file, it  `Failed to find 'colors.css/myth/variables'` https://github.com/basscss/addons/blob/master/modules/colors/index.css#L3

I could manually install this dependency , but I'm wondering how and where this should have been installed?

Cheers!

**Comment by jxnblk** [comment]
Are you using npm 3 or an older version? I need to add a note about that in the docs...

**Comment by oller** [comment]
```
→ npm -v
3.3.12
```

**Comment by oller** [comment]
Bumping to `3.7.3` with a fresh `npm i` the error still occurs...

```
postcss-import: /static/node_modules/basscss-addons/modules/background-colors/index.css:3:1: Failed to find 'colors.css/myth/variables'
    in [
        /static/node_modules/basscss-addons/modules/background-colors
    ]
```

Am I missing something as I'm upgrading bassplate from v7 to v8.  I ported over all the package.json changes....

I can check node_modules and `colors.css` is never installed, and even when I do install it the path still doesn't resolve.

**Comment by jxnblk** [comment]
So, I _think_ I know what's happening: Individual modules have `colors.css` as a dependency, but the root `basscss-addons` package didn't. I've added it to the root package.json. Can you try with `basscss-addons@1.0.0-beta3`?

**Comment by oller** [comment]
No dice i'm afraid, bumped and rebuild `node_modules`, still no luck.

The source of the problem I'm sure stems from:
https://github.com/basscss/addons/blob/master/modules/colors/index.css#L3

As i'm not sure how that path is resolved.

Even changing the path to : 

```
@import '../colors.css/myth/variables';
```

Which would be the correct relative path within the flat `node_modules` still fails.

As it stands, if I do an npm list for colors.css the only result I get is installed under addons.

```
│ ├── basscss-type-scale@1.0.5
│ └── basscss-typography@3.0.3
├─┬ basscss-addons@1.0.0-beta3
│ └── colors.css@3.0.0
├── basscss-basic@1.0.0
├─┬ browser-sync@2.11.1
```

I'm trying to build this with the bassplate postcss workflow.

**Comment by danielredwood** [comment]
@oller same game here

**Comment by rdsubhas** [comment]
Problem with folder being named as `myth`. I changed that to:

```
@import 'colors.css/src/_variables';
```

And it works... Maybe its a change in colors.css?

**Comment by rdsubhas** [comment]
Pretty much yes. colors.css upgraded to v3.0.0 and is backwards incompatible, the `myth` folder is no longer present. aka the myth folder is now myth.

**Comment by rdsubhas** [comment]
don't depend on basscss-addons directly for now. use the individual modules separately from npm...

**Comment by jxnblk** [comment]
Thanks! I bumped all the modules up to `colors.css@3.0.0`, and I think it should work now, but let me know if the issue persists.

**Comment by zekenie** [comment]
I'm still running into this issue when I use the package as a whole and the individual packages
