### ISSUE TITLE
forms CDN missing

### ISSUE THREAD

**Issue by drschwabe** [basscss/addons#9]
There is no scripts.prepublish in this module's package.json

**Comment by jxnblk** [comment]
Sorry if it's unclear. Forms does not need a republish script since it's just vanilla CSS. The CDN link is here: https://npmcdn.com/basscss-addons/modules/forms/index.css

**Comment by drschwabe** [comment]
Oh ok, thanks for clarifying. 

@jxnblk one thing that might be useful, in the interest of convenience/rapid drop-in since that is the intention of the CDN links, is a quick menu (ie- in the addons Readme) with links to all of the latest CDNs.

**Comment by jxnblk** [comment]
Yeah, I would suggest using npm if you tend to use the addons much, but could be helpful for Code Pen/prototyping. I'd accept a PR if you wanna take a stab :)

**Comment by drschwabe** [comment]
Hmm ok I might consider that.  I guess the best way would probably be a pre-publish style script for the addons module itself that parses each addon's package.json for the version number, builds a CDN URL (while also considering modules that are just in vanilla CSS; which have different URL pattern),   ammends those URLs as links in the addon Readme file, and then commits the change.

**Comment by jxnblk** [comment]
I wouldn't want to make it overly complicated. I _think_ npmcdn supports leaving the version number off to get the latest, and manually maintaining a list in the README doesn't seem all that bothersome.
